package POJO;
// Generated Oct 18, 2022 3:37:44 PM by Hibernate Tools 4.3.1


import DAO.DAOCustomer;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Customer generated by hbm2java
 */
@ManagedBean
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String idGame;
     private String payment;
     private String total;
     private String phone;

        
     // Umtuk menampilkan data ke table
    public List<Customer> getAllRecords() {
        DAOCustomer customer = new DAOCustomer();
        List<Customer> listCustomer = customer.retrveCustomer();
        return listCustomer;
    }
    
    public String getById() {
        String idCustomer = id.toString();
        DAOCustomer customer = new DAOCustomer();
        List<Customer> listCustomer = customer.getbyID(idCustomer);
        try {
            if (listCustomer != null) {
                id = listCustomer.get(0).id;
                idGame = listCustomer.get(0).idGame;
                payment = listCustomer.get(0).payment;
                total = listCustomer.get(0).total;
                phone = listCustomer.get(0).phone;
                return "Data Customer";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "Data Customer";
    }
    
    
    
  public String save_customer() {
        DAOCustomer add = new DAOCustomer();
        return add.add_customer(this);
    }
    
    
     public String editCustomer() {
        DAOCustomer customer = new DAOCustomer();
        customer.editCustomer(this);
        idGame = "";
        payment = "";
        total = "";
        phone = "";
        return "Data Customer";
    }
    
    public String deleteCustomer() {
        DAOCustomer customer = new DAOCustomer();
        customer.deleteCustomer(id);
         idGame = "";
        payment = "";
        total = "";
        phone = "";
        return "Data Customer";
    }
    
//    public List<Customer> getBy(String uName, String uPass) {
//        Transaction trans = null;
//        Customer cust = new Customer();
//        List<Customer> customer = new ArrayList();
//        Session session = UcTopUpUtil.getSessionFactory().openSession();
//        
//        try {
//            trans = session.beginTransaction();
//            Query query = session.createQuery("from User where username=:uName AND password=:uPass");
//            query.setString("uName", uName);
//            query.setString("uPass", uPass);
//            us = (User) query.uniqueResult();
//            user = query.list();
//            trans.commit();
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        return user;
//    }
//

    
    public Customer() {
    }

    public Customer(int id, String idGame, String payment, String total, String phone) {
       this.id = id;
       this.idGame = idGame;
       this.payment = payment;
       this.total = total;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIdGame() {
        return this.idGame;
    }
    
    public void setIdGame(String idGame) {
        this.idGame = idGame;
    }
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


