package POJO;
// Generated Oct 18, 2022 3:37:44 PM by Hibernate Tools 4.3.1


import DAO.DAOAdmin;
import DAO.DAOLogin;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * User generated by hbm2java
 */
@ManagedBean
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

      // Umtuk menampilkan data ke table
    public List<User> getAllRecords() {
        DAOAdmin user = new DAOAdmin();
        List<User> listUser = user.retrveUser();
        return listUser;
    }
    
    public String getbyID() {
        String idUser = id.toString();
        DAOAdmin user = new DAOAdmin();
        List<User> listUser = user.getbyID(idUser);
        try {
            if (listUser != null) {
                id = listUser.get(0).id;
                username = listUser.get(0).username;
                password = listUser.get(0).password;
                return "dashboard";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "dashboard";
    }
    
  //  public String getbyID() {
    //    String idUser = id.toString();
     //   DAOAdmin user = new DAOAdmin();
      //  List<User> listUser = user.getbyID(idUser);
      //  username =  listUser.get(0).username;
       // password = listUser.get(0).password;
       // return "dashboard";
    //}
    
    
    
     public String save_user() {
        DAOLogin add = new DAOLogin();
        return add.add_user(this);
    }
    
    public String login_user() {
        DAOLogin uDao = new DAOLogin();
        List<User> us = uDao.getBy(username, password);
        try {
            if (us != null) {
                username = us.get(0).username;
                password = us.get(0).password;
                return "dashboard";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "Failed";
    }
    
    public String editUser() {
        DAOAdmin admin = new DAOAdmin();
        admin.editUser(this);
        username = "";
        password = "";
        return "dashboard";
    }
    
    public String deleteUser() {
        DAOAdmin admin = new DAOAdmin();
        admin.deleteUser(id);
        username = "";
        password = "";
        return "dashboard";
    }
     
     
    public User() {
    }

    public User(int id, String username, String password) {
       this.id = id;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


